# documentation: https://conda-forge.org/docs/maintainer/conda_forge_yml.html
channels:
  sources:
    - zeroae
    - conda-forge
    - defaults
  targets:
    - ["zeroae", "main"]
azure:
  user_or_org: zeroae
github:
  user_or_org: zeroae
  branch: master